name: "GREEN: Test Build sdist"

# export tt=build_arts-g
# git tag -d "$tt"; git push --delete origin "$tt";
# git tag "$tt" && git push origin "$tt"

# export tt=build_arts-g && git tag -d "$tt"; git push --delete origin "$tt"; git tag "$tt" && git push origin "$tt"

# Test Scenario:
# When we only make an 'sdist' build; Source Distro / .tar.gz
# Test Suite Passes and Produces 1 File Artifact

# When downloading artifacts, the .tar.gz file should be there

on:
  workflow_dispatch:
  push:
    branches:
      - "test"
    tags:
      - "all"
      - "build"
      - "build_arts-g"


jobs:
  call_test_build_job:
    uses: boromir674/automated-workflows/.github/workflows/test_build.yml@test
    with:
      build_installation: 'sdist'
      job_matrix: "{\"platform\": [\"ubuntu-latest\"], \"python-version\": [\"3.11\"]}"
      typecheck_policy: '0'

  download_artifacts:
    needs: call_test_build_job
    runs-on: ubuntu-latest
    steps:
      # WEHN we download Artifacts from CI
      - name: Download 
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist-local
      # THEN there are only 1 Files (no more, no less)
      # AND the .tar.gz file is there

      # ASSERT LIST OF FILES HAS 1 ITEMS
      - name: List Files
        run: |
          ARTIFACT_FILES=$(ls -la dist-local)
          echo "ARTIFACT_FILES: $ARTIFACT_FILES"
          ARTIFACT_FILES_COUNT=$(ls -la dist-local | wc -l)
          echo "ARTIFACT_FILES_COUNT: $ARTIFACT_FILES_COUNT"
          if [ "$ARTIFACT_FILES_COUNT" -ne "4" ]; then
            echo "ERROR: Expected only 1 .tar.gz File, got $ARTIFACT_FILES_COUNT"
            exit 1
          fi

      # ASSERT .tar.gz FILE IS THERE, loop over and check file name
      - name: Assert only minimal_python-0.0.1.tar.gz file in loop
        run: |
          for file in dist-local/*; do
            echo "file: $file"
            if [ "$file" != "dist-local/minimal_python-0.0.1.tar.gz" ]; then
              echo "ERROR: Expected only minimal_python-0.0.1.tar.gz File, got $file"
              exit 1
            fi
          done
