name: "GREEN: Test Build Caller Pol 1"

on:
  workflow_dispatch:
  push:
    branches:
      - "test"
    tags:
      - "all"
      - "build"
      - "build-g"

jobs:
  call_test_build_job:
    uses: boromir674/automated-workflows/.github/workflows/test_build.yml@test
    with:
      # OS, Python, Build "mode"
      # verified working: edit sdist
      build_installation: 'edit wheel'
      job_matrix: "{\"platform\": [\"ubuntu-latest\"], \"python-version\": [\"3.11\"]}"

      run_policy: '1'
      typecheck_policy: '1'
