name: "GREEN: Test Build Caller Pol 1"

# export tt=build_arts-g
# git tag -d "$tt"; git push --delete origin "$tt";
# git tag "$tt" && git push origin "$tt"

# export tt=build_arts-g && git tag -d "$tt"; git push --delete origin "$tt"; git tag "$tt" && git push origin "$tt"

# Test Scenario:
# When we build with default parameters
# Test Suite Passes and Produces Artifacts

# When downloading artifacts, the .tar.gz file should be there

on:
  workflow_dispatch:
  push:
    branches:
      - "test"
    tags:
      - "all"
      - "build"
      - "build_arts-g"


jobs:
  call_test_build_job:
    uses: boromir674/automated-workflows/.github/workflows/test_buld.yml@test
    with:
      build_installation: 'sdist wheel'
      job_matrix: "{\"platform\": [\"ubuntu-latest\"], \"python-version\": [\"3.11\"]}"
      typecheck_policy: '0'

  download_artifacts:
    needs: call_test_build_job
    runs-on: ubuntu-latest
    steps:
      # WEHN we download Artifacts from CI
      - name: Download 
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist-local
      # THEN there are only 2 Files (no more, no less)
      # AND the .tar.gz file is there
      # AND the .whl file is there

      # ASSERT LIST OF FILES HAS 2 ITEMS
      - name: List Files
        run: |
          ARTIFACT_FILES=$(ls -la dist-local)
          echo "ARTIFACT_FILES: $ARTIFACT_FILES"
          ARTIFACT_FILES_COUNT=$(ls -la dist-local | wc -l)
          echo "ARTIFACT_FILES_COUNT: $ARTIFACT_FILES_COUNT"
          if [ "$ARTIFACT_FILES_COUNT" -ne "5" ]; then
            echo "ERROR: Expected 2 Files, got $ARTIFACT_FILES_COUNT"
            exit 1
          fi
      # ASSERT .tar.gz FILE IS THERE
      
      # ASSERT .whl FILE IS THERE
      - name: List Files
        run: |
          ls -la dist-local
