name: "GREEN: Test Build Caller Pol 1"

on:
  workflow_dispatch:
  push:
    branches:
      - "test"
    tags:
      - "all"
      - "build"
      - "build-g"

jobs:
  call_test_build_job:
    uses: boromir674/automated-workflows/.github/workflows/test_buld.yml@test
    with:
      distro_name: minimum_python
      pep440_version: '0.0.1'
      run_policy: '1'
      typecheck_policy: '1'

      # OS, Python, Build "mode"
      build_installation: 'edit sdist wheel'
      job_matrix: "{\"platform\": [\"ubuntu-latest\"], \"python-version\": [\"3.10\", \"3.11\"]}"
    